version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_DATABASE}
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "${PHP_MY_ADMIN_PORT:-8080}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${WORDPRESS_PORT:-8000}:80"
    restart: always
    volumes: ['./wp-content/plugins:/var/www/html/wp-content/plugins', './wp-content/themes:/var/www/html/wp-content/themes']
    environment:
      WORDPRESS_DB_HOST: db:${WORDPRESS_DB_HOST:-3306}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: